# Generated by Django 3.1.1 on 2020-09-18 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200917_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'cart'), (1, 'buy')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 18, 13, 13, 53, 565023)),
        ),
    ]
