# Generated by Django 3.1.1 on 2020-09-18 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200918_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 18, 13, 16, 45, 278463)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'cart'), (1, 'buy')], default=0),
        ),
    ]
