# Generated by Django 3.1.1 on 2020-09-18 14:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=500, null=True)),
                ('apartment', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(max_length=300, null=True)),
                ('pincode', models.CharField(max_length=50, null=True)),
                ('phone_no', models.IntegerField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 18, 20, 24, 24, 328636))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
