# Generated by Django 3.1.1 on 2020-11-23 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_address', '0007_auto_20200919_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 24, 1, 49, 40, 856219)),
        ),
    ]
