# Generated by Django 3.1.3 on 2020-11-26 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_address', '0009_auto_20201126_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 26, 11, 38, 43, 425251)),
        ),
    ]
