# Generated by Django 3.1.1 on 2020-09-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1),
        ),
    ]
